language: python
#version
python:
  - "2.7"
cache: pip
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database bucketlist_test'; -U postgres
script:
  - nosetests --with-coverage --cover-package=app

after_success: coveralls